import type { OperationalRescueStatus } from '~/constants/operational-kanban';

export interface RescueCardDetail {
  id: number;
  folio: string;
  service_type: string;
  client_id: number;
  client_name: string;
  service_description: string;
  location_description: string;
  sale_price: string | null;
  operative_status: OperationalRescueStatus;
  operator_id: number | null;
  operator_name: string | null;
  supplier_id: number | null;
  supplier_name: string | null;
  multiple_managers: boolean;
  sub_total: string | null;
  admin_status: string;
  created_at: string;
  phase_started_at: string;
  unlocked_until: string | null;
  client_type: string;
  client_phone: string | null;
  seller_id: number | null;
  seller_name: string | null;
  vehicle: string | null;
  internal_notes?: string | null;
  provider_cost: string | null;
  net_profit: string | null;
  supplier_score: number | null;
  latitude: string | null;
  longitude: string | null;
  quote_count?: number;
  advance_amount?: string | number | null;
  advance_requested?: boolean;
  advance_received?: boolean | null;
  advance_date?: string | null;
  advance_payment_method?: string | null;
  advance_reference?: string | null;
  close_date?: string | null;
  disbursement_date?: string | null;
  disbursement_payment_method?: string | null;
  credit_limit?: string | number | null;
  credit_available?: number | null;
  assigned_suppliers?: {
    id: number;
    name: string;
  }[];
}
